/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package window;

import control.FuncoesUteis;
import control.GenericTableModel;
import control.GerenciadorInterGrafica;
import java.lang.reflect.InvocationTargetException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class BuscaGenerica extends javax.swing.JDialog {
    
    public static enum TipoPesquisa{
        STRING,
        INT,
        ENUM,
        FOREIGN_KEY,
        DATE
    }
    
    public static enum Modo {
        SELECAO,
        EDICAO
    }
    
    private GenericTableModel table_model = null;
    private Object objeto_selecionado = null;
    private final Class classe;
    private Modo modo;
    private TipoPesquisa tipo_pesquisa;
    private Object foreign_key_object = null;
    private Class foreign_key_class = null;
            
    /**
     * Creates new form BuscaInstituicao
     * @param parent
     * @param modal
     * @param classe
     */
    public BuscaGenerica(java.awt.Frame parent, boolean modal, Class classe) {
        super(parent, modal);
        initComponents();
        
        this.classe = classe;
        this.table_model = new GenericTableModel(this.classe);
        this.tableBusca.setModel(table_model);
        this.modo = Modo.SELECAO;
        
        for(int i = 0; i < tableBusca.getColumnCount(); ++i){
            cmBoxOpcoes.addItem(tableBusca.getColumnName(i));
        }
        
    }
    
    public void setModo(Modo modo){
        this.modo = modo;
    }

    @Override
    public void setVisible(boolean b) {
        switch (this.modo) {
            case EDICAO:
                selectOrEditButton.setText("Editar");
                break;
            case SELECAO:
                selectOrEditButton.setText("Selecionar");
        }
        super.setVisible(b); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    public Object getObjetoSelecionado() {
        return objeto_selecionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusca = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBusca = new javax.swing.JTable();
        panelBotoes = new javax.swing.JPanel();
        panelSelecionar = new javax.swing.JPanel();
        selectOrEditButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        panelPesquisa = new javax.swing.JPanel();
        botaoPesquisar = new javax.swing.JButton();
        cmBoxOpcoes = new javax.swing.JComboBox<>();
        cmBoxPesqEnum = new javax.swing.JComboBox<>();
        fieldData = new javax.swing.JFormattedTextField();
        fieldPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableBusca);

        javax.swing.GroupLayout panelBuscaLayout = new javax.swing.GroupLayout(panelBusca);
        panelBusca.setLayout(panelBuscaLayout);
        panelBuscaLayout.setHorizontalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        panelBuscaLayout.setVerticalGroup(
            panelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        selectOrEditButton.setText("Selecionar");
        selectOrEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectOrEditButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelecionarLayout = new javax.swing.GroupLayout(panelSelecionar);
        panelSelecionar.setLayout(panelSelecionarLayout);
        panelSelecionarLayout.setHorizontalGroup(
            panelSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecionarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectOrEditButton)
                .addGap(18, 18, 18)
                .addComponent(excluirButton)
                .addGap(18, 18, 18)
                .addComponent(novoButton)
                .addGap(18, 18, 18)
                .addComponent(cancelarButton)
                .addGap(16, 16, 16))
        );
        panelSelecionarLayout.setVerticalGroup(
            panelSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelecionarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelSelecionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectOrEditButton)
                    .addComponent(cancelarButton)
                    .addComponent(novoButton)
                    .addComponent(excluirButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addComponent(panelSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        botaoPesquisar.setText("🔍");
        botaoPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        cmBoxOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxOpcoesActionPerformed(evt);
            }
        });

        try {
            fieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesquisaLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(cmBoxPesqEnum, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesquisaLayout.createSequentialGroup()
                    .addContainerGap(138, Short.MAX_VALUE)
                    .addComponent(fieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmBoxOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cmBoxPesqEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPesquisaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        List<Object> lista = new ArrayList<>();
       
        if (null != tipo_pesquisa) switch (tipo_pesquisa) {
            case ENUM:
                lista = GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().pesquisarPorInt
                        (classe, table_model.getPersistenceColumnName(cmBoxOpcoes.getSelectedIndex()), cmBoxPesqEnum.getSelectedIndex());
                break;
            case FOREIGN_KEY:
                foreign_key_object = GerenciadorInterGrafica.getInstance().abrirBusca(foreign_key_class);
                fieldPesquisa.setText(foreign_key_object.toString());
                
                int id = 0;
                try {
                    id = (int) foreign_key_class.getMethod("getId").invoke(foreign_key_object);
                } catch (NoSuchMethodException | SecurityException | IllegalAccessException | InvocationTargetException ex) {
                    Logger.getLogger(BuscaGenerica.class.getName()).log(Level.SEVERE, null, ex);
                } 
                
                lista = GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().pesquisarPorForeignKey
                        (classe, table_model.getPersistenceColumnName(cmBoxOpcoes.getSelectedIndex()), id);
                break;
            case STRING:
                lista = GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().pesquisarPorString
                        (classe, table_model.getPersistenceColumnName(cmBoxOpcoes.getSelectedIndex()), fieldPesquisa.getText());
                break;
            case INT:
                lista = GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().pesquisarPorInt
                        (classe, table_model.getPersistenceColumnName(cmBoxOpcoes.getSelectedIndex()), Integer.parseInt(fieldPesquisa.getText()));
                break;
            case DATE:
                try {
                    lista = GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().pesquisarPorData
                                (classe, table_model.getPersistenceColumnName(cmBoxOpcoes.getSelectedIndex()), FuncoesUteis.strToDate(fieldData.getText()));
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Insira uma data válida.");
                }
        }
        
        table_model.setList(lista);    
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void selectOrEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectOrEditButtonActionPerformed
        int linha = tableBusca.getSelectedRow();
        try{
            objeto_selecionado = table_model.getObjectAt(linha);
            if (modo == Modo.EDICAO) {
                GerenciadorInterGrafica.getInstance().abrirCad(objeto_selecionado, classe);
                botaoPesquisarActionPerformed(evt);
                objeto_selecionado = null;
            } else {
                this.setVisible(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para realizar a ação.", "", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_selectOrEditButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        GerenciadorInterGrafica.getInstance().abrirCad(objeto_selecionado, classe);
        botaoPesquisarActionPerformed(evt);
    }//GEN-LAST:event_novoButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        int linha = tableBusca.getSelectedRow();
        if(linha >= 0){
            objeto_selecionado = table_model.getObjectAt(linha);
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir a linha selecionada?", "Excluir", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().excluir(objeto_selecionado);
                botaoPesquisarActionPerformed(evt);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.", "", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void cmBoxOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxOpcoesActionPerformed
        int i = cmBoxOpcoes.getSelectedIndex();
        Class classe_field = table_model.getFieldClass(i);
        
        fieldPesquisa.setText("");
        
        if (classe_field.isEnum()) {
            fieldData.setVisible(false);
            cmBoxPesqEnum.removeAllItems();
            fieldPesquisa.setVisible(false);
            cmBoxPesqEnum.setVisible(true);
            Object[] enum_values = classe_field.getEnumConstants();
            for (Object enum_value : enum_values) {
                cmBoxPesqEnum.addItem(enum_value.toString());
            }
            tipo_pesquisa = TipoPesquisa.ENUM;
        } else if (table_model.haveFieldManyToOneAnnotation(i)){
            fieldPesquisa.setVisible(true);
            fieldPesquisa.setEditable(true);
            cmBoxPesqEnum.setVisible(false);
            fieldData.setVisible(false);
            foreign_key_class = classe_field;
            tipo_pesquisa = TipoPesquisa.FOREIGN_KEY;
            fieldPesquisa.setEditable(false);
        } else if (classe_field == Date.class){
            fieldData.setVisible(true);
            fieldPesquisa.setVisible(false);
            cmBoxPesqEnum.setVisible(false);
            tipo_pesquisa = TipoPesquisa.DATE;
        } else {
            fieldData.setVisible(false);
            fieldPesquisa.setVisible(true);
            fieldPesquisa.setEditable(true);
            cmBoxPesqEnum.setVisible(false);            
            if (classe_field == String.class){
                tipo_pesquisa = TipoPesquisa.STRING;
            } else if (classe_field == int.class) {
                tipo_pesquisa = TipoPesquisa.INT;
            }
        }
        

    }//GEN-LAST:event_cmBoxOpcoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> cmBoxOpcoes;
    private javax.swing.JComboBox<String> cmBoxPesqEnum;
    private javax.swing.JButton excluirButton;
    private javax.swing.JFormattedTextField fieldData;
    private javax.swing.JTextField fieldPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoButton;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JPanel panelSelecionar;
    private javax.swing.JButton selectOrEditButton;
    private javax.swing.JTable tableBusca;
    // End of variables declaration//GEN-END:variables
}
