/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package window;

import control.FuncoesUteis;
import control.GenericTableModel;
import control.GerenciadorInterGrafica;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Acao;
import model.Executor;
import model.Instituicao;
import model.Local;
import model.Participante;

/**
 *
 * @author gabriel
 */
public class CadastroAcao extends CadJDialog<Acao> {

    /**
     * Creates new form CadastroAcao
     */
    
    private GenericTableModel table_inst = new GenericTableModel(Instituicao.class);
    private GenericTableModel table_exec = new GenericTableModel(Executor.class);
    private GenericTableModel table_part = new GenericTableModel(Participante.class);
    
    private List lista_inst = new ArrayList();
    private List lista_exec = new ArrayList();
    private List lista_part = new ArrayList();
            
    private Local local_selecionado = null;
            
    public CadastroAcao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tableExecutor.setModel(table_exec);
        table_exec.setList(lista_exec);
        
        tableInstituicao.setModel(table_inst);
        table_inst.setList(lista_inst);
        
        tableParticipante.setModel(table_part);
        table_part.setList(lista_part);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        cmBoxTipo = new javax.swing.JComboBox<>();
        labelInicio = new javax.swing.JLabel();
        labelFim = new javax.swing.JLabel();
        labelCargaHoraria = new javax.swing.JLabel();
        spinnerCargaHoraria = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescricao = new javax.swing.JTextArea();
        panelInsti = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInstituicao = new javax.swing.JTable();
        addInst = new javax.swing.JButton();
        panelExec = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableExecutor = new javax.swing.JTable();
        addExec = new javax.swing.JButton();
        panelPart = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableParticipante = new javax.swing.JTable();
        addPart = new javax.swing.JButton();
        panelButton = new javax.swing.JPanel();
        cancelarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        localField = new javax.swing.JTextField();
        buscarLocal = new javax.swing.JButton();
        inicioText = new javax.swing.JFormattedTextField();
        fimText = new javax.swing.JFormattedTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        nomeLabel.setText("Nome:");

        labelTipo.setText("Tipo:");

        cmBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oficina", "Curso", "Palestra", "Visita Técnica" }));

        labelInicio.setText("Início:");

        labelFim.setText("Fim:");

        labelCargaHoraria.setText("Carga Horária:");

        spinnerCargaHoraria.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        textDescricao.setColumns(20);
        textDescricao.setLineWrap(true);
        textDescricao.setRows(3);
        jScrollPane1.setViewportView(textDescricao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane2.setViewportView(tableInstituicao);

        addInst.setText("Adicionar");
        addInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInstiLayout = new javax.swing.GroupLayout(panelInsti);
        panelInsti.setLayout(panelInstiLayout);
        panelInstiLayout.setHorizontalGroup(
            panelInstiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstiLayout.createSequentialGroup()
                .addGroup(panelInstiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addInst)))
                .addContainerGap())
        );
        panelInstiLayout.setVerticalGroup(
            panelInstiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstiLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addInst))
        );

        jScrollPane3.setViewportView(tableExecutor);

        addExec.setText("Adicionar");
        addExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExecLayout = new javax.swing.GroupLayout(panelExec);
        panelExec.setLayout(panelExecLayout);
        panelExecLayout.setHorizontalGroup(
            panelExecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExecLayout.createSequentialGroup()
                .addGroup(panelExecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExecLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addExec)))
                .addContainerGap())
        );
        panelExecLayout.setVerticalGroup(
            panelExecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExecLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addExec))
        );

        jScrollPane6.setViewportView(tableParticipante);

        addPart.setText("Adicionar");
        addPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPartLayout = new javax.swing.GroupLayout(panelPart);
        panelPart.setLayout(panelPartLayout);
        panelPartLayout.setHorizontalGroup(
            panelPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartLayout.createSequentialGroup()
                .addGroup(panelPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPartLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPart)))
                .addContainerGap())
        );
        panelPartLayout.setVerticalGroup(
            panelPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPart))
        );

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(salvarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarButton)
                .addGap(40, 40, 40))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(salvarButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText("Local:");

        localField.setEditable(false);

        buscarLocal.setText("🔍");
        buscarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLocalActionPerformed(evt);
            }
        });

        try {
            inicioText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            fimText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInsti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelExec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelInicio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inicioText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelFim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fimText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCargaHoraria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spinnerCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buscarLocal))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo)
                    .addComponent(cmBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelInicio)
                        .addComponent(labelFim)
                        .addComponent(labelCargaHoraria)
                        .addComponent(spinnerCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fimText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inicioText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(localField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInsti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(panelExec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLocalActionPerformed

        local_selecionado = (Local) GerenciadorInterGrafica.getInstance().abrirBuscaLocal(BuscaGenerica.Modo.SELECAO);
        
        if(local_selecionado != null){
            localField.setText(local_selecionado.toString());
        }
    }//GEN-LAST:event_buscarLocalActionPerformed

    private void addInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstActionPerformed
        Object obj = GerenciadorInterGrafica.getInstance().abrirBuscaInstituicao(BuscaGenerica.Modo.SELECAO);
        if(obj != null){
            lista_inst.add(obj);
            table_inst.setList(lista_inst);
        }
    }//GEN-LAST:event_addInstActionPerformed

    private void addExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExecActionPerformed
        Object obj = GerenciadorInterGrafica.getInstance().abrirBuscaExecutor(BuscaGenerica.Modo.SELECAO);
        
        if(obj != null){
            lista_exec.add(obj);
            table_exec.setList(lista_exec);
        }
    }//GEN-LAST:event_addExecActionPerformed

    private void addPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartActionPerformed
        Object obj = GerenciadorInterGrafica.getInstance().abrirBuscaParticipante(BuscaGenerica.Modo.SELECAO);
        
        if(obj != null){
            lista_part.add(obj);
            table_part.setList(lista_part);
        }
    }//GEN-LAST:event_addPartActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        String nome = nomeField.getText();
        Acao.Tipo tipo = Acao.Tipo.values()[cmBoxTipo.getSelectedIndex()];
        int carga_horaria = (int)spinnerCargaHoraria.getValue();
        String descricao = textDescricao.getText();
        Date fim = new Date();
        Date inicio = new Date();
        try {
            fim = FuncoesUteis.strToDate(fimText.getText());
            inicio = FuncoesUteis.strToDate(inicioText.getText());
        } catch (ParseException ex) {
            Logger.getLogger(CadastroAcao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if ( objectToBeEdited == null){
            GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().inserirAcao(inicio, fim, carga_horaria, nome, descricao, tipo, local_selecionado, lista_inst, lista_part, lista_exec);
        } else {
            GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().alterarAcao(objectToBeEdited.getId(), inicio, fim, carga_horaria, nome, descricao, tipo, local_selecionado, lista_inst, lista_part, lista_exec);
        }
        GerenciadorInterGrafica.getInstance().getSubjectAcoes().setState(
        GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().listarAcoes());
        this.setVisible(false);
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExec;
    private javax.swing.JButton addInst;
    private javax.swing.JButton addPart;
    private javax.swing.JButton buscarLocal;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> cmBoxTipo;
    private javax.swing.JFormattedTextField fimText;
    private javax.swing.JFormattedTextField inicioText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel labelCargaHoraria;
    private javax.swing.JLabel labelFim;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField localField;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelExec;
    private javax.swing.JPanel panelInsti;
    private javax.swing.JPanel panelPart;
    private javax.swing.JButton salvarButton;
    private javax.swing.JSpinner spinnerCargaHoraria;
    private javax.swing.JTable tableExecutor;
    private javax.swing.JTable tableInstituicao;
    private javax.swing.JTable tableParticipante;
    private javax.swing.JTextArea textDescricao;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void preencherDados() {
        GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().carregarAcao(objectToBeEdited);
        
        nomeField.setText(objectToBeEdited.getNome());
        cmBoxTipo.setSelectedIndex(objectToBeEdited.getTipo().ordinal());
        try {
            inicioText.setText(FuncoesUteis.dateToStr(objectToBeEdited.getDtInicio()));
            fimText.setText(FuncoesUteis.dateToStr(objectToBeEdited.getDtFim()));
        } catch (ParseException ex) {
            Logger.getLogger(CadastroAcao.class.getName()).log(Level.SEVERE, null, ex);
        }
        spinnerCargaHoraria.setValue(objectToBeEdited.getCargaHoraria());
        local_selecionado = objectToBeEdited.getLocal();
        localField.setText(local_selecionado.toString());
        textDescricao.setText(objectToBeEdited.getDescricao());
        
        lista_inst = objectToBeEdited.getInstituicoes();
        table_inst.setList(lista_inst);
        
        lista_exec = objectToBeEdited.getExecutores();
        table_exec.setList(lista_exec);
        
        lista_part = objectToBeEdited.getParticipantes();
        table_part.setList(lista_part);
        
    }

    @Override
    protected void limparDados() {
        nomeField.setText("");
        cmBoxTipo.setSelectedIndex(0);
        
        inicioText.setText("");
        fimText.setText("");
        
        spinnerCargaHoraria.setValue(0);
        local_selecionado = null;
        localField.setText("");
        textDescricao.setText("");
        
        lista_inst = new ArrayList();
        table_inst.setList(lista_inst);
        
        lista_exec = new ArrayList();
        table_exec.setList(lista_exec);
        
        lista_part = new ArrayList();
        table_part.setList(lista_part);
    }
}
