/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package window;

import control.GerenciadorInterGrafica;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Executor;
import model.Instituicao;
import model.Participante;
import model.Pessoa;

/**
 *
 * @author gabriel
 */
public class CadastroPessoa extends CadJDialog<Pessoa> {

    @Override
    protected void preencherDados() {
        nomeField.setText(objectToBeEdited.getNome());
        cpfField.setText(objectToBeEdited.getCpf());
        emailField.setText(objectToBeEdited.getEmail());
        switch (tipo_pessoa) {
            case EXECUTOR:
                final Executor executor = (Executor) objectToBeEdited;
                cmbTipo.setSelectedIndex(executor.getTipo().ordinal());
                break;
            case PARTICIPANTE:
                final Participante participante = (Participante) objectToBeEdited;
                instituicao_selecionada = participante.getInstituicao();
                nomeInst.setText(instituicao_selecionada.toString());
        }
    }

    @Override
    protected void limparDados() {
        nomeField.setText("");
        cpfField.setText("");
        emailField.setText("");
        switch (tipo_pessoa) {
            case EXECUTOR:
                cmbTipo.setSelectedIndex(0);
                break;
            case PARTICIPANTE:
                instituicao_selecionada = null;
                nomeInst.setText("");
        }
    }

    public static enum TipoPessoa{
        EXECUTOR,
        PARTICIPANTE;
    }
    
    TipoPessoa tipo_pessoa;
    
    Instituicao instituicao_selecionada = null;
    /**
     * Creates new form CadastrarParticipante
     * @param parent
     * @param modal
     * @param tipo_pessoa
     */
    public CadastroPessoa(java.awt.Frame parent, boolean modal, TipoPessoa tipo_pessoa) {
        super(parent, modal);
        initComponents();
        switch (tipo_pessoa) {
            case EXECUTOR:
                painelExecutor.setVisible(true);
                painelParticipante.setVisible(false);
                break;
            case PARTICIPANTE:
                painelExecutor.setVisible(false);
                painelParticipante.setVisible(true);
                break;
        }
        this.tipo_pessoa = tipo_pessoa;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        cpfField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        painel = new javax.swing.JPanel();
        painelParticipante = new javax.swing.JPanel();
        labelInst = new javax.swing.JLabel();
        nomeInst = new javax.swing.JTextField();
        buttonInst = new javax.swing.JButton();
        painelExecutor = new javax.swing.JPanel();
        labelTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        salvarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelNome.setText("Nome:");

        labelCPF.setText("CPF:");

        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email:");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        labelInst.setText("Instituição:");

        nomeInst.setEditable(false);

        buttonInst.setText("🔍");
        buttonInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelParticipanteLayout = new javax.swing.GroupLayout(painelParticipante);
        painelParticipante.setLayout(painelParticipanteLayout);
        painelParticipanteLayout.setHorizontalGroup(
            painelParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParticipanteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelInst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeInst, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelParticipanteLayout.setVerticalGroup(
            painelParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelParticipanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInst)
                    .addComponent(nomeInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInst))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelTipo.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discente Voluntário", "Discente Bolsista", "Servidor", "Colaborador Externo" }));

        javax.swing.GroupLayout painelExecutorLayout = new javax.swing.GroupLayout(painelExecutor);
        painelExecutor.setLayout(painelExecutorLayout);
        painelExecutorLayout.setHorizontalGroup(
            painelExecutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelExecutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        painelExecutorLayout.setVerticalGroup(
            painelExecutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelExecutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelExecutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelParticipante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painelExecutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addComponent(painelParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelLayout.createSequentialGroup()
                    .addComponent(painelExecutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(salvarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarButton)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        
        String nome = nomeField.getText();
        String cpf = cpfField.getText();
        String email = emailField.getText();
        
        if (objectToBeEdited == null) {
            switch (tipo_pessoa) {
                case EXECUTOR:
                    GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().inserirExecutor(nome, cpf, email, Executor.Tipo.values()[cmbTipo.getSelectedIndex()]);
                    break;
                case PARTICIPANTE:
                    GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().inserirParticipante(nome, cpf, email, instituicao_selecionada);
            }
        } else {
            switch (tipo_pessoa) {
                case EXECUTOR:
                    GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().alterarExecutor(objectToBeEdited.getId(), nome, cpf, email, Executor.Tipo.values()[cmbTipo.getSelectedIndex()]);
                    break;
                case PARTICIPANTE:
                    GerenciadorInterGrafica.getInstance().getGerenciadorDeDominio().alterarParticipante(objectToBeEdited.getId(), nome, cpf, email, instituicao_selecionada);
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void buttonInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInstActionPerformed
        instituicao_selecionada = (Instituicao) GerenciadorInterGrafica.getInstance().abrirBuscaInstituicao(BuscaGenerica.Modo.SELECAO);
        nomeInst.setText(instituicao_selecionada.toString());
    }//GEN-LAST:event_buttonInstActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInst;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JTextField cpfField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelInst;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField nomeInst;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painelExecutor;
    private javax.swing.JPanel painelParticipante;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
